#undef MANUFACTURER
#undef PRODUCT
#undef DEBOUNCE
#undef PRODUCT_ID

#define MANUFACTURER    Anaheim Electronics
#define PRODUCT         DZ60 Unicorn Keyboard
#define PRODUCT_ID      0x2260

#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION
#define DEBOUNCE 3
#define TIMEOUT_DELAY 900

//RGB Matrix Effects
#define RGB_MATRIX_KEYPRESSES                                // Keypress effects
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS                       // Frame buffer effects
#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_CYCLE_LEFT_RIGHT  //default mode
//disable standard effects
#define DISABLE_RGB_MATRIX_ALPHAS_MODS
#define DISABLE_RGB_MATRIX_BAND_SAT
#define DISABLE_RGB_MATRIX_BAND_VAL
#define DISABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#define DISABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#define DISABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#define DISABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#define DISABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#define DISABLE_RGB_MATRIX_RAINDROPS
//disable keypress effects
#define DISABLE_RGB_MATRIX_SOLID_REACTIVE
#define DISABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#define DISABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#define DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#define DISABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#define DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#define DISABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#define DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXU
#define DISABLE_RGB_MATRIX_MULTISPLASH

//RGB Matrix Config
#define RGB_DISABLE_WHEN_USB_SUSPENDED true // turn off effects when suspended
#define DRIVER_LED_TOTAL 100                // The number of LEDs connected
#define RGB_DI_PIN E2                       // Assign to pin E2 on DZ60 board
#define RGBLIGHT_SLEEP
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 255
#define RGB_MATRIX_STARTUP_VAL 255
#define RGB_MATRIX_STARTUP_SPD 64