#define USB_POLLING_INTERVAL_MS 2
#define QMK_KEYS_PER_SCAN 8
#define DEBOUNCE 2

/* USB Device descriptor parameter */
#undef VENDOR_ID
#undef PRODUCT
#define VENDOR_ID    0x4B52 //KP - Updated to match default firmware
#define PRODUCT      Lithglow980

#define FORCE_NKRO

// RGB Matrix
#ifdef RGB_MATRIX_ENABLE
    #define RGB_MATRIX_MAXIMUM_BRIGHTNESS 190
    #define RGB_DISABLE_WHEN_USB_SUSPENDED
    #define RGB_DISABLE_TIMEOUT 900000 // 15 minutes

    //RGB Matrix Effects
    #define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
    #define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
    #define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
    #define ENABLE_RGB_MATRIX_CYCLE_SPIRAL
    #define ENABLE_RGB_MATRIX_RAINBOW_BEACON
    #define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
    #define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN

    #define ENABLE_RGB_MATRIX_TYPING_HEATMAP

    #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
    #define ENABLE_RGB_MATRIX_SOLID_REACTIVE

    #define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_CUSTOM_HUE_PENDULUM2
    #define RGB_MATRIX_STARTUP_HUE 135
    #define RGB_MATRIX_STARTUP_SPD 64

    #define RGB_MATRIX_FRAMEBUFFER_EFFECTS
    #define RGB_MATRIX_KEYPRESSES

    // This allows VIA to control RGB Matrix settings in the 'Lighting' section.
    #define VIA_QMK_RGBLIGHT_ENABLE
#endif
